# Generated by Django 4.1.7 on 2023-02-28 06:41

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("item", models.CharField(max_length=100)),
                ("description", models.CharField(max_length=100)),
                ("price", models.IntegerField()),
                ("image", models.ImageField(upload_to="")),
            ],
        ),
    ]
